### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by intelliot** [jeffcarp/rcrd#15]
What determines the colors? They don't seem to be consistent (`records` shows a cat in one color, while `cats` shows it in a different one, even within the same page). Also, colors appear to differ between rcrd.org and localhost.

**Comment by jeffcarp** [comment]
My idea was that the color of a records' cats would correspond to the time of day, so that if you were looking at all your workouts, for example, you could tell at a glance whether they clustered around a certain time. The implementation of this, as you discovered, is not consistent or complete. The function that converts time of day into a 0-255 hue value is here: https://github.com/jeffcarp/rcrd/blob/master/app/helpers/application_helper.rb#L6

**Comment by jeffcarp** [comment]
Colors are now determined by converting individual category strings into a number between 0 and 255, which is given to the `hue` part of a `hsl()` CSS rule:
https://github.com/jeffcarp/rcrd/blob/master/browser/util.js#L51
https://github.com/jeffcarp/rcrd/blob/master/browser/cat.js#L35

It ends up looking like this:

![screen shot 2016-03-29 at 2 44 42 pm](https://cloud.githubusercontent.com/assets/916028/14124868/d079e572-f5bc-11e5-9341-e7ed332c0497.png)

(If you know of a smarter way to do this please let me know)

(Also there are no docs on running the repo in its current state so if you're interested in getting it up and running let's pair)
